name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main  # Or the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create deployment zip
        run: zip -r deploy_package.zip . -x "*.git*" "*/.git*" "*/.github*" "*.ipynb_checkpoints*"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1 # Updated region

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: MLProject
          environment_name: MLProject-env
          region: eu-north-1 # Updated region
          version_label: ${{github.sha}}
          deployment_package: deploy_package.zip
